Name:           ros-jade-image-common
Version:        1.11.12
Release:        0%{?dist}
Summary:        ROS image_common package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/image_common
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-jade-camera-calibration-parsers
Requires:       ros-jade-camera-info-manager
Requires:       ros-jade-image-transport
Requires:       ros-jade-polled-camera
BuildRequires:  ros-jade-catkin

%description
Common code for working with images in ROS.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Sun Jan 29 2017 Jack O'Quin <jack.oquin@gmail.com> - 1.11.12-0
- Autogenerated by Bloom

* Sat Sep 24 2016 Jack O'Quin <jack.oquin@gmail.com> - 1.11.11-0
- Autogenerated by Bloom

* Tue Jan 19 2016 Jack O'Quin <jack.oquin@gmail.com> - 1.11.10-0
- Autogenerated by Bloom

* Sun Jan 17 2016 Jack O'Quin <jack.oquin@gmail.com> - 1.11.9-0
- Autogenerated by Bloom

* Sun Nov 29 2015 Jack O'Quin <jack.oquin@gmail.com> - 1.11.8-0
- Autogenerated by Bloom

* Tue Jul 28 2015 Jack O'Quin <jack.oquin@gmail.com> - 1.11.7-0
- Autogenerated by Bloom

* Thu Jul 16 2015 Jack O'Quin <jack.oquin@gmail.com> - 1.11.6-0
- Autogenerated by Bloom

* Thu May 14 2015 Jack O'Quin <jack.oquin@gmail.com> - 1.11.5-0
- Autogenerated by Bloom

* Thu Jan 01 2015 Jack O'Quin <jack.oquin@gmail.com> - 1.11.4-0
- Autogenerated by Bloom

